---

DEVICE : "cuda:0" # cuda:0
DEBUG :
    ENABLE : False
    NUM_SAMPLES : 20 
    

# -----------------------------------------------------------------------------
# Dataset
# -------------------------------------------------------------------------
DATASET :
    NUMBER_OF_POINTS : 1024 
    GRAPH_BUILD_METHOD: "knn" #knn| ballquery
    K_NUM_CONNECTIONS : 15
    MAX_CONNECTIONS: 20000
    RADIUS: 0.1


# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
DATALOADER :
    BATCH_SIZE : 4 
    NUM_WORKERS : 4 
    CACHE : False 


MODEL :
    NAME : "PN"  # PN | PN2 | GPN | GPN2
    NORMAL_CHANNEL : True
    GNN:
        GRAPH_TYPE: "GCN" # GCN | GAT
        N_LAYERS: 3
        HEADS: 3
        DROPOUT: 0.5


# ---------------------------------------------------------------------------- #
# Solver
# ---------------------------------------------------------------------------- #
SOLVER :
    LR : 0.001 
    EPOCHS : 200 
    MIN_LR : 1.0e-5 
    LR_DECAY : 0.5 
    LR_STEP_SIZE : 20


# ---------------------------------------------------------------------------- #
# Specific train options
# ---------------------------------------------------------------------------- #
TRAIN :
    SAVE_CHECKPOINT : True 
    SAVE_CHECKPOINT_PATH : "checkpoints/GPN/GPN.pth" 
    LOAD_CHECKPOINT : False 
    LOAD_CHECKPOINT_PATH : "checkpoints/GPN/GPN.pth" 
    WANDB_LOG : True
    WANDB_PROJECT : "GPN" 
    WANDB_SAVE_MODEL : True 
    EARLY_STOPPING : True 
    PATIENCE : 10
    RESTORE_BEST_WEIGHTS : True


# ---------------------------------------------------------------------------- #
# Specific test options
# ---------------------------------------------------------------------------- #
TEST :
    LOAD_CHECKPOINT_PATH : "checkpoints/GPN/GPN.pth" 
    VISUALIZE : False 


...